spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemedecineapi
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: f8U5x7V9w2q5z8YbW3k9v6JdN1r2t4p8o1q2r3s4t5u6v7w8x9y0z1a2b3c4d5
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


logging:
  level:
    com.telemedecine.api.mapper: DEBUG
    org.mapstruct: DEBUG